#!/usr/bin/env python3
"""Render Nginx allow directives from the internal profile environment file."""

from __future__ import annotations

import argparse
import ipaddress
import sys

from profile_config import EnvFileError, parse_env_file


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render internal Nginx CIDR allowlist."
    )
    parser.add_argument("--env", default="/etc/agenthub/internal.env")
    args = parser.parse_args()
    try:
        env = parse_env_file(args.env)
    except EnvFileError as exc:
        print(f"[FAIL] ENV_FILE: {exc}", file=sys.stderr)
        return 2

    raw_values = [
        item.strip() for item in env.get("INTERNAL_ALLOWED_CIDRS", "").split(",")
    ]
    values = [item for item in raw_values if item]
    if not values:
        print("[FAIL] internal allowlist is empty", file=sys.stderr)
        return 1

    networks: list[str] = []
    for value in values:
        try:
            network = ipaddress.ip_network(value, strict=False)
        except ValueError:
            print(
                "[FAIL] internal allowlist contains a non-CIDR entry", file=sys.stderr
            )
            return 1
        if network.prefixlen == 0:
            print(
                "[FAIL] internal allowlist must not allow the entire Internet",
                file=sys.stderr,
            )
            return 1
        networks.append(str(network))

    print(
        "# Generated by render_nginx_allowlist.py; deny all remains in the site template."
    )
    for network in networks:
        print(f"allow {network};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
