"""initial schema mysql

Revision ID: 36240c81e0d1
Revises: 
Create Date: 2026-06-20 11:35:22.165075
"""

from alembic import op
import sqlalchemy as sa


revision = '36240c81e0d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('issued_for_phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_key_issued_for_phone', 'api_key', ['issued_for_phone'], unique=False)
    op.create_index('ix_api_key_key_prefix', 'api_key', ['key_prefix'], unique=False)
    op.create_index('ix_api_key_owner', 'api_key', ['owner_type', 'owner_id'], unique=False)
    op.create_table('org_unit',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('org_unit_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('external_phone_uk', sa.String(length=32), sa.Computed("(CASE WHEN user_type = 'EXTERNAL_CUSTOMER' THEN phone_normalized ELSE NULL END)", persisted=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_account_email', 'user_account', ['email'], unique=False)
    op.create_index('ix_user_account_phone_normalized', 'user_account', ['phone_normalized'], unique=False)
    op.create_index('uq_user_account_external_phone', 'user_account', ['external_phone_uk'], unique=True)
    op.create_table('agent',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_org_unit_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_type', sa.String(length=50), nullable=False),
    sa.Column('runtime_app_id', sa.String(length=200), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['owner_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_agent_code')
    )
    op.create_index('ix_agent_owner', 'agent', ['owner_org_unit_id'], unique=False)
    op.create_table('auth_session',
    sa.Column('session_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_index('ix_auth_session_idle_expires', 'auth_session', ['idle_expires_at'], unique=False)
    op.create_index('ix_auth_session_revoked', 'auth_session', ['revoked_at'], unique=False)
    op.create_index('ix_auth_session_user', 'auth_session', ['user_id'], unique=False)
    op.create_table('embed_session',
    sa.Column('session_hash', sa.String(length=128), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=False),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_index('ix_embed_session_agent_code', 'embed_session', ['agent_code'], unique=False)
    op.create_index('ix_embed_session_expires_at', 'embed_session', ['expires_at'], unique=False)
    op.create_index('ix_embed_session_external_user', 'embed_session', ['external_user_id'], unique=False)
    op.create_index('ix_embed_session_hash', 'embed_session', ['session_hash'], unique=False)
    op.create_index('ix_embed_session_status', 'embed_session', ['status'], unique=False)
    op.create_index('ix_embed_session_user', 'embed_session', ['user_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_org_unit_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_kb_id', sa.String(length=200), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('retrieval_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['owner_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_base_owner', 'knowledge_base', ['owner_org_unit_id'], unique=False)
    op.create_index('ix_knowledge_base_provider_kb', 'knowledge_base', ['provider', 'provider_kb_id'], unique=False)
    op.create_table('lead_contact',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('contact_value', sa.String(length=255), nullable=True),
    sa.Column('phone_normalized', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_normalized', name='uq_lead_contact_phone_normalized')
    )
    op.create_index('ix_lead_contact_org', 'lead_contact', ['org_unit_id'], unique=False)
    op.create_index('ix_lead_contact_user', 'lead_contact', ['user_id'], unique=False)
    op.create_table('permission_policy',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_resource', 'permission_policy', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_permission_subject', 'permission_policy', ['subject_type', 'subject_id'], unique=False)
    op.create_table('agent_invocation_record',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('caller_type', sa.String(length=32), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('stream_mode', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invocation_agent_created', 'agent_invocation_record', ['agent_id', 'created_at'], unique=False)
    op.create_index('ix_invocation_api_key_created', 'agent_invocation_record', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_invocation_org_created', 'agent_invocation_record', ['org_unit_id', 'created_at'], unique=False)
    op.create_index('ix_invocation_request_id', 'agent_invocation_record', ['request_id'], unique=False)
    op.create_table('agent_knowledge_base',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'knowledge_base_id', name='uq_agent_knowledge_base')
    )
    op.create_index('ix_agent_kb_agent', 'agent_knowledge_base', ['agent_id'], unique=False)
    op.create_index('ix_agent_kb_kb', 'agent_knowledge_base', ['knowledge_base_id'], unique=False)
    op.create_table('conversation',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('agent_code', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_conversation_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_agent_user', 'conversation', ['agent_id', 'user_id'], unique=False)
    op.create_index('ix_conversation_user_last_message', 'conversation', ['user_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversation_user_status_last_message', 'conversation', ['user_id', 'status', 'last_message_at'], unique=False)
    op.create_table('document',
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('owner_org_unit_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_uri', sa.String(length=500), nullable=True),
    sa.Column('provider_doc_id', sa.String(length=200), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('chunk_version', sa.String(length=100), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ),
    sa.ForeignKeyConstraint(['owner_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_kb', 'document', ['knowledge_base_id'], unique=False)
    op.create_index('ix_document_provider_doc', 'document', ['provider_doc_id'], unique=False)
    op.create_table('conversation_message',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('invocation_record_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['invocation_record_id'], ['agent_invocation_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_message_conversation_created', 'conversation_message', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_conversation_message_conversation_sequence', 'conversation_message', ['conversation_id', 'sequence_no'], unique=False)
    op.create_table('sales_lead',
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('agent_code', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_summary', sa.Text(), nullable=True),
    sa.Column('requirement_types', sa.JSON(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['lead_contact.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_lead_contact', 'sales_lead', ['contact_id'], unique=False)
    op.create_index('ix_sales_lead_conversation', 'sales_lead', ['conversation_id'], unique=False)
    op.create_index('ix_sales_lead_user_agent_status', 'sales_lead', ['user_id', 'agent_id', 'status'], unique=False)
    op.create_table('lead_capture_event',
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_message_id', sa.String(length=36), nullable=True),
    sa.Column('invocation_record_id', sa.String(length=36), nullable=True),
    sa.Column('sales_lead_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('agent_code', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_unit_id', sa.String(length=36), nullable=True),
    sa.Column('raw_delta', sa.JSON(), nullable=False),
    sa.Column('normalized_delta', sa.JSON(), nullable=False),
    sa.Column('followup_decision', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['lead_contact.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['conversation_message_id'], ['conversation_message.id'], ),
    sa.ForeignKeyConstraint(['invocation_record_id'], ['agent_invocation_record.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['sales_lead_id'], ['sales_lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_capture_event_conversation', 'lead_capture_event', ['conversation_id'], unique=False)
    op.create_index('ix_lead_capture_event_invocation', 'lead_capture_event', ['invocation_record_id'], unique=False)
    op.create_index('ix_lead_capture_event_lead', 'lead_capture_event', ['sales_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL 中 drop_table 会自动连带删除该表的索引与外键，
    # 因此无需逐个 drop_index（逐个删除反而会因外键依赖报 1553）。
    # 按外键依赖逆序删除即可。
    op.drop_table('lead_capture_event')
    op.drop_table('sales_lead')
    op.drop_table('conversation_message')
    op.drop_table('document')
    op.drop_table('conversation')
    op.drop_table('agent_knowledge_base')
    op.drop_table('agent_invocation_record')
    op.drop_table('permission_policy')
    op.drop_table('lead_contact')
    op.drop_table('knowledge_base')
    op.drop_table('embed_session')
    op.drop_table('auth_session')
    op.drop_table('agent')
    op.drop_table('user_account')
    op.drop_table('org_unit')
    op.drop_table('api_key')
